yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    FIRST_FIFTEEN_CHARACTERS = 15
    text = models.TextField(verbose_name='Текст статьи',
                            help_text='Введите текст статьи')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации',
                                    help_text='Укажите дату '
                                              'публикации')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор статьи',
                               help_text='Укажите автора статьи')
    group = models.ForeignKey('Group', blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа статей',
                              help_text='Выберите тематическую группу '
                                        'в выпадающем списке по желанию')
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:Post.FIRST_FIFTEEN_CHARACTERS]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы',
                             help_text='Введите название тематической группы')
    slug = models.SlugField(unique=True, verbose_name='Номер группы',
                            help_text='Укажите порядковый номер группы')
    description = models.TextField(verbose_name='Описание группы',
                                   help_text='Добавьте текст описания группы')

    class Meta:
        verbose_name = 'Группа статей'
        verbose_name_plural = 'Группы статей'
        ordering = ('-title',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Комментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор публикации'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Напишите комментарий',
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True,
    )

    def __str__(self):
        return self.text[:30]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'], name='unique_following'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control',
                                                   'rows': 7}),
            'group': forms.Select(attrs={'class': 'form-control'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import CommentForm, PostForm
from posts.models import Group, Post, Follow

User = get_user_model()


def page_look(post_list, page_number):
    paginator = Paginator(post_list, settings.VIEW_COUNT)
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    post_list = Post.objects.select_related('author', 'group')
    page_obj = page_look(post_list, request.GET.get('page'))
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_posts = author.posts.select_related('group')
    page_obj = page_look(author_posts, request.GET.get('page'))
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    posts_count = post.author.posts.count()
    comments = post.comments.select_related('author')
    context = {
        'post': post,
        'posts_count': posts_count,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    page_obj = page_look(post_list, request.GET.get('page'))
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post_create = form.save(commit=False)
        post_create.author = request.user
        post_create.save()
        return redirect('posts:profile', post_create.author)
    template = 'posts/post_create.html'
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if post.author != request.user:
        messages.error(request, 'You are not authorized to edit this post.')
        return redirect('posts:post_detail', post_id)

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = (Post.objects
                 .select_related('author', 'group')
                 .filter(author__following__user=request.user))
    page_obj = page_look(post_list, request)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user, author__username=username).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  {% block title %}
    Мои подписки
  {% endblock %}
  {% block content %} 
  {% include 'includes/switcher.html' with follow=True %}
    <div class="container py-5">      
      <h1>Последние обновления моих подписок</h1>
      {% for post in page_obj %}
          {% include 'includes/post_item.html' %}
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </div>
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{  group.title  }}
{% endblock title %}

{% block content %}
      <div>
        <h1>{{  group.title  }}</h1>
        <p>{{  group.description  }}</p>
        {% for post in page_obj %}
        {% include "includes/post_item.html" with post=post hide_author_link=False show_group_link=False %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% if page_obj.has_other_pages %}
            {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
        {% endif %}
      </div>    
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  {% load cache %}
  {% include 'includes/switcher.html' with index=True %}
      {% cache 20 index page_obj.number %}
      {% for post in page_obj %}
        {% include "includes/post_item.html" with post=post hide_author_link=False show_group_link=True %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% endcache %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %} {% if edit %} Редактировать запись {% else %} Добавить запись {% endif %} {% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data">
            
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary btn-block">{% if is_edit %}Сохранить{% else %}Добавить запись{% endif %}</button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div> 

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}

  {{  post.title|truncatechars:30  }}
  
{% endblock title %} 

{% block content %}
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{  post.pub_date |date:"D d M Y"  }}
              </li>
              <li class="list-group-item">
                Группа: {{  post.group  }}
                <a href="{% url 'posts:group_list' post.group.slug %}" class="text-secondary">
                  все записи группы
                </a>
              </li>
              <li class="list-group-item">
                Автор: {{  post.author  }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ user.posts.all.count }}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            <p>{{  post.text|linebreaksbr  }}</p>
            {% if post.author == user %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
              редактировать запись
            </a>
            {% endif %}

            {% include 'includes/comment.html' %}

          </article>
        </div>
      </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{  author.get_full_name  }}{% endblock title %}

{% block content %} 
<div class="mb-5">       
    <h1>Все посты пользователя {{  author  }}</h1>
    <h3>Всего постов: {{  author.posts.all.count  }}</h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
</div>
    <hr>
      {% for post in page_obj %}
      {% include "includes/post_item.html" with post=post hide_author_link=True show_group_link=True %} 
      {% endfor %}
      {% if page_obj.has_other_pages %}
            {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
      {% endif %}
  </div>
{% endblock content %}